version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: module_4/Part_1/requirements.txt

sphinx:
  configuration: module_4/Part_1/docs/source/conf.py
